apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wooridaum
patches:
- path: domain.json
  target:
    kind: Ingress
    name: ingress
resources:
- ../../base
- namespace.yaml
images:
- name: sce06147/wooridaum
  newTag: 5f0c661960aa0d2763d0a11996cae6e42f554be0
